<?php 
// Display errors if any
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

// Retrieve the token generate by Checkout.Frames and POSTED here.
$cardToken = $_POST['cko_card_token'];
$paymentType = $_POST['payment_type'];

// The api endpoint and the authorisation key
$apiUrl = "https://api.sandbox.checkout.com/payments";
$apiKey = "sk_test_07fa5e52-3971-4bab-ae6b-a8e26007fccc";  // Default channel

if ($paymentType === "bancaire"){ 
	echo('<pre>'.$paymentType.'</pre>');
	$apiKey = "sk_test_072b329f-39c6-4ac3-aadb-d28029b676eb"; // Carte Bancaire channel
}
echo('<pre>'.$apiKey.'</pre>');

// The request body that will be sent in the API call
$requestBody = json_encode(array(
	'source' => array(
		'type' => 'token',
		'token' => $cardToken // generated by Checkout.Frames
	),
	'amount' => '2499',
	'currency' => 'GBP',
	'reference' => 'test order 123'
));

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$apiUrl);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'Authorization: '.$apiKey,
    'Content-Type:application/json;charset=UTF-8'
    ));
curl_setopt($ch, CURLOPT_POSTFIELDS, $requestBody);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$server_output = curl_exec($ch);
curl_close ($ch);

// The payment response
$response = json_decode($server_output);

// Print payment response to screen
echo('<pre>'.print_r($response, true).'</pre>');

exit();
?>